### ISSUE TITLE
Latest chromium build breaks ssl on google servers

### ISSUE THREAD

**Issue by isage** [RussianFedora/chromium#2]
See https://code.google.com/p/chromium/issues/detail?id=567282

**Comment by xvitaly** [comment]
Gmail, Google Accounts, Search and other Google services works fine for me on Chromium 47.0.2526.73 Russian Fedora (64-bit). OpenSSL version: 1.0.2e-fips (3 Dec 2015). Fedora 23.

**Comment by isage** [comment]
Someone reported it on #fedora channel on irc today.
It's sometimes works after cleaning cache. Anyways, chromiums devs says it's not supported configuration, so we shouldn't use it.

**Comment by isage** [comment]
Oh, wait, it was fixed in https://github.com/RussianFedora/chromium/commit/cfc27cd2a48e4d3e96937b023330ae64f39cbbc6
Sorry.

**Comment by ghost** [comment]
Блин, вы оба говорите на русском, так что вам мешает общаться между собой на русском?

**Comment by Tigro** [comment]
On github we should speak only in English.
