### ISSUE TITLE
hardware vaapi does not work fedora 23

### ISSUE THREAD

**Issue by arpu** [RussianFedora/chromium#3]
vainfo 
libva info: VA-API version 0.38.1
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_38
libva info: va_openDriver() returns 0
vainfo: VA-API version: 0.38 (libva 1.6.2)
vainfo: Driver version: Intel i965 driver for Intel(R) Haswell Mobile - 1.6.2
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264MultiviewHigh      : VAEntrypointVLD
      VAProfileH264StereoHigh         : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileJPEGBaseline           : VAEntrypointVLD

Version 48.0.2564.82 Russian Fedora (64-bit)

chromium
libva info: VA-API version 0.38.1
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
[6787:6787:0124/165643:ERROR:vaapi_wrapper.cc(340)] vaInitialize failed VA error: unknown libva error
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
[6693:6693:0124/165703:ERROR:CONSOLE(402)] "Uncaught TypeError: Cannot read property 'gpu_memory_buffer_info' of undefined", source: chrome://gpu/gpu_internals.js (402)

**Comment by arpu** [comment]
chromium  --no-sandbox
works

can you add this patch? 
https://codereview.chromium.org/15955009/diff/92001/content/common/sandbox_linux/bpf_gpu_policy_linux.cc

**Comment by arpu** [comment]
@Tigro

**Comment by Tigro** [comment]
Hi!

This patch is broken, I can't apply it on chromium 48 :(

**Comment by Tigro** [comment]
@arpu I fount rewrited patch here http://www.slackware.com/~alien/slackbuilds/chromium/build/patches/chromium_vaapi.patch

When package will be built, I leave here link to test.

**Comment by Tigro** [comment]
I've tested patch, but it buggy for nvidia. Vdpau crashes with it.

But I think you should enable this parameter to enable Video Decode: chrome://flags/#ignore-gpu-blacklist

Also to enable Hardware Rasterization switch on this parameter: chrome://flags/#enable-gpu-rasterization

**Comment by arpu** [comment]
ok tested with both chromium flags
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
[6831:6831:0131/131102:ERROR:vaapi_wrapper.cc(340)] vaInitialize failed VA error: unknown libva error

can you upload  your rpm with the patch ? i can test on intel

**Comment by Tigro** [comment]
Try latest from here http://koji.russianfedora.pro/koji/packageinfo?packageID=11

I have tested it on intel and NVIDIA proprietary driver.

**Comment by arpu** [comment]
hello can not find the rpm with build patch :/ 

koji latest is 48.0.2564.103
and no newer rpms on churchyard/copr

**Comment by Tigro** [comment]
Try this: http://koji.russianfedora.pro/koji/buildinfo?buildID=2551

**Comment by arpu** [comment]
same as bevore 

hardware acceleration works with --no-sandbox   but not without

**Comment by Tigro** [comment]
Please screen first paragraph of chrome://gpu/
Also did you enable 

chrome://flags/#ignore-gpu-blacklist
chrome://flags/#enable-gpu-rasterization

flags?

**Comment by Tigro** [comment]
This is my chrome://gpu in Chromium 48.0.2564.103 Russian Fedora (64-bit)

![_060](https://cloud.githubusercontent.com/assets/534335/13068743/84655c5a-d48f-11e5-8f8c-1293c132dcbd.png)

**Comment by arpu** [comment]
Graphics Feature Status
Canvas: Hardware accelerated
Flash: Hardware accelerated
Flash Stage3D: Hardware accelerated
Flash Stage3D Baseline profile: Hardware accelerated
Compositing: Hardware accelerated
Multiple Raster Threads: Disabled
Rasterization: Hardware accelerated
Video Decode: Hardware accelerated
Video Encode: Hardware accelerated
WebGL: Hardware accelerated

but this does not say vaapi works! 
always get the sandbox error .... 
start chromium in the console 
chromium --no-sandbox
libva info: VA-API version 0.38.1
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_38
libva info: va_openDriver() returns 0

chromium 
libva info: VA-API version 0.38.1
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
[3456:3456:0222/134743:ERROR:vaapi_wrapper.cc(340)] vaInitialize failed VA error: unknown libva error

play any video on vimio (h264) and you see the cpu usage different 

tested with Version 48.0.2564.116 Russian Fedora (64-bit)

**Comment by Tigro** [comment]
You can try this build: http://koji.russianfedora.pro/koji/buildinfo?buildID=2641
I think it works proper on Intel, but crash on NVIDIA proprietary.

**Comment by Tigro** [comment]
$ chromium 
libva info: VA-API version 0.38.1
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_38
libva info: va_openDriver() returns 0
libva info: VA-API version 0.38.1
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_38
libva info: va_openDriver() returns 0

**Comment by arpu** [comment]
libva info: VA-API version 0.38.1
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/nvidia_drv_video.so
libva info: Found init function __vaDriverInit_0_38
libva info: va_openDriver() returns 0
libva info: VA-API version 0.38.1
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/nvidia_drv_video.so
libva info: Found init function __vaDriverInit_0_38
Received signal 8 FPE_INTDIV 7efe04a3029a
#0 0x7efe2f6af4d8 <unknown>
#1 0x7efe288979f0 <unknown>
#2 0x7efe04a3029a <unknown>
#3 0x7efe04a33088 <unknown>
#4 0x7efe04a330d6 <unknown>
#5 0x7efe04a332ac <unknown>
#6 0x7efe04a34090 <unknown>
#7 0x7efe13f610b6 <unknown>
#8 0x7efe13f61ed7 vaInitialize
#9 0x7efe3643facd content::VaapiWrapper::VADisplayState::Initialize()
#10 0x7efe3643dd70 content::VaapiWrapper::VaInitialize()
#11 0x7efe3644304d content::VaapiWrapper::LazyProfileInfos::LazyProfileInfos()
#12 0x7efe3643e4a1 content::VaapiWrapper::GetSupportedDecodeProfiles()
#13 0x7efe36436399 content::VaapiVideoDecodeAccelerator::GetSupportedProfiles()
#14 0x7efe362b41b7 <unknown>
#15 0x7efe362d9f71 <unknown>
#16 0x7efe35d8a9af <unknown>
#17 0x7efe35d89860 content::ContentMain()
#18 0x55c24de95358 <unknown>
#19 0x7efe24e4a580 __libc_start_main
#20 0x55c24de95209 <unknown>
  r8: 0000000000000000  r9: fefefefefefeff30 r10: 00007ffcd3cda493 r11: 0000000000000202
 r12: 0000000000000000 r13: 00007ffcd3cda674 r14: 00007efe04a3d6cc r15: 00000a11fde9ae00
  di: 00000a11fde9af50  si: 0000000000000000  bp: 0000000000000000  bx: 00000a11fde9af50
  dx: 0000000000000000  ax: 0000000000000000  cx: 0000000000000000  sp: 00007ffcd3cda650
  ip: 00007efe04a3029a efl: 0000000000010246 cgf: 0000000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
[22526:22548:0224/025212:ERROR:browser_gpu_channel_host_factory.cc(132)] Failed to launch GPU process.

yes same here, crash on NVIDIA proprietary.

will test this on intel next weekend

any idea about the nvidea bug?

**Comment by Tigro** [comment]
No ideas at this time. The other day I'll try to install Ubuntu on NVIDIA host and check whether there is such error.

**Comment by Tigro** [comment]
I've tested vaapi builds (ppa:saiarcot895/chromium-beta) on Ubuntu 15.04. It crashes on nouveau too. With nvidia drivers chromium does not crash, but libva returns -1 during chromium start, so it does not work proper too.

Stable version of ubuntu chromium is not patched with vaapi patch.

**Comment by arpu** [comment]
i test more on nvidea it "works" with --no-sandbox 
so 
1, there is a sandbox problem
2, vaapi_wrapper does not work with nvidea vdpau

chromium --no-sandbox --ppapi-flash-path=/opt/google/chrome/PepperFlash/libpepflashplayer.so  
[5258:5258:0224/142602:ERROR:browser_main_loop.cc(206)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
libva info: VA-API version 0.38.1
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/nvidia_drv_video.so
libva info: Found init function __vaDriverInit_0_38
libva info: va_openDriver() returns 0
[5364:5364:0224/142603:ERROR:vaapi_wrapper.cc(446)] vaQuerySurfaceAttributes failed VA error: invalid parameter
[5364:5364:0224/142603:ERROR:vaapi_wrapper.cc(301)] GetMaxResolution failed for va_profile 0 and entrypoint 1
[5364:5364:0224/142603:ERROR:vaapi_wrapper.cc(446)] vaQuerySurfaceAttributes failed VA error: invalid parameter
[5364:5364:0224/142603:ERROR:vaapi_wrapper.cc(301)] GetMaxResolution failed for va_profile 1 and entrypoint 1
[5364:5364:0224/142603:ERROR:vaapi_wrapper.cc(446)] vaQuerySurfaceAttributes failed VA error: invalid parameter
[5364:5364:0224/142603:ERROR:vaapi_wrapper.cc(301)] GetMaxResolution failed for va_profile 2 and entrypoint 1
[5364:5364:0224/142603:ERROR:vaapi_wrapper.cc(446)] vaQuerySurfaceAttributes failed VA error: invalid parameter
[5364:5364:0224/142603:ERROR:vaapi_wrapper.cc(301)] GetMaxResolution failed for va_profile 3 and entrypoint 1
[5364:5364:0224/142603:ERROR:vaapi_wrapper.cc(446)] vaQuerySurfaceAttributes failed VA error: invalid parameter
[5364:5364:0224/142603:ERROR:vaapi_wrapper.cc(301)] GetMaxResolution failed for va_profile 5 and entrypoint 1
[5364:5364:0224/142603:ERROR:vaapi_wrapper.cc(446)] vaQuerySurfaceAttributes failed VA error: invalid parameter
[5364:5364:0224/142603:ERROR:vaapi_wrapper.cc(301)] GetMaxResolution failed for va_profile 6 and entrypoint 1
[5364:5364:0224/142603:ERROR:vaapi_wrapper.cc(446)] vaQuerySurfaceAttributes failed VA error: invalid parameter
[5364:5364:0224/142603:ERROR:vaapi_wrapper.cc(301)] GetMaxResolution failed for va_profile 7 and entrypoint 1
[5364:5364:0224/142603:ERROR:vaapi_wrapper.cc(446)] vaQuerySurfaceAttributes failed VA error: invalid parameter
[5364:5364:0224/142603:ERROR:vaapi_wrapper.cc(301)] GetMaxResolution failed for va_profile 8 and entrypoint 1
[5364:5364:0224/142603:ERROR:vaapi_wrapper.cc(446)] vaQuerySurfaceAttributes failed VA error: invalid parameter
[5364:5364:0224/142603:ERROR:vaapi_wrapper.cc(301)] GetMaxResolution failed for va_profile 9 and entrypoint 1
[5364:5364:0224/142603:ERROR:vaapi_wrapper.cc(446)] vaQuerySurfaceAttributes failed VA error: invalid parameter
[5364:5364:0224/142603:ERROR:vaapi_wrapper.cc(301)] GetMaxResolution failed for va_profile 10 and entrypoint 1
vdpau_video: vaTerminate(): config ID 0x01000000 is still allocated, destroying
vdpau_video: vaTerminate(): config ID 0x01000001 is still allocated, destroying
vdpau_video: vaTerminate(): config ID 0x01000002 is still allocated, destroying
vdpau_video: vaTerminate(): config ID 0x01000003 is still allocated, destroying
vdpau_video: vaTerminate(): config ID 0x01000004 is still allocated, destroying
vdpau_video: vaTerminate(): config ID 0x01000005 is still allocated, destroying
vdpau_video: vaTerminate(): config ID 0x01000006 is still allocated, destroying
vdpau_video: vaTerminate(): config ID 0x01000007 is still allocated, destroying
vdpau_video: vaTerminate(): config ID 0x01000008 is still allocated, destroying
vdpau_video: vaTerminate(): config ID 0x01000009 is still allocated, destroying
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
NOT SANDBOXED
Vector smash protection is enabled.
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
[5364:5364:0224/142634:ERROR:gpu_video_decode_accelerator.cc(375)] HW video decode not available for profile 1
[5364:5364:0224/142709:ERROR:gpu_video_decode_accelerator.cc(375)] HW video decode not available for profile 1

**Comment by arpu** [comment]
works with 
00:02.0 VGA compatible controller: Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 09)
libva info: VA-API version 0.38.1
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_38
libva info: va_openDriver() returns 0

**Comment by Tigro** [comment]
I've found out why Chromium crashed with libva-vdpau-driver and nvidia.

This patch fix this issue: https://github.com/RussianFedora/libva-vdpau-driver/commit/c4074c5290abec67ed09f24bba9d37935b48deeb

VAAPI does not work with nvidia as before, but also does not crash, so if no any regressions will be found I will build next 49 chromium with vaapi.

**Comment by Tigro** [comment]
Heh. It also crashes in Virtual Hosts. I think we should wait for more stable support of VAAPI. Maybe VAAPI version of chromium will be built in updates-testing.

**Comment by arpu** [comment]
Heh do  you have any news on this? because it would be greate to decode some 4k VP9 videos withs intels Kaby Lake (hardware vp9 encoders)

**Comment by xvitaly** [comment]
@arpu Fedora 23 already reached it's EOL. Upgrade to Fedora 26.

**Comment by Tigro** [comment]
@xvitaly you are a bit off topic. @arpu I didn't try to build chromium with vaapi support since. Maybe try later after my vacation.

**Comment by arpu** [comment]
https://chromium-review.googlesource.com/c/532294/

looks like chrome 62 will get this for intel gpu!
